-- REVOLUTION POS — veprimtaritë e reja për regjistrim (Super Admin telefon)
-- Restorant, Kafene, Bar, Lounge bar, Pub, Fast food, Pizzeri, Doner / Kebab,
-- Gjelltore, Fish restaurant, Sushi bar.
-- Tipet e vjetra mbeten të lejuara (klientë ekzistues).

ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_tipi_check;

ALTER TABLE public.clients ADD CONSTRAINT clients_tipi_check
  CHECK (tipi IN (
    'restorant',
    'kafene',
    'bar',
    'lounge_bar',
    'pub',
    'fast_food',
    'piceri',
    'doner_kebab',
    'gjelltore',
    'fish_restaurant',
    'sushi_bar',
    'klub_nate',
    'dyqan_pijesh',
    'pub_lounge',
    'bar_nate',
    'klub',
    'diskoteke',
    'kebab',
    'pasticeri',
    'akullore',
    'gjeltore',
    'furre_buke',
    'hotel_restorant',
    'hotel',
    'motel',
    'hostel',
    'resort',
    'ville_me_qira',
    'ville',
    'bujtine',
    'market',
    'minimarket',
    'mini_market',
    'pilar',
    'supermarket',
    'dyqan_ushqimor',
    'manav',
    'bulmetore',
    'kasap',
    'peshkore',
    'dyqan_peshku',
    'dyqan_rroba',
    'dyqan_kepuce',
    'dyqan',
    'farmaci',
    'optike',
    'berber',
    'sallon_bukurie',
    'tjeter'
  ));
